---
name: Dicop-Server
author: BSI
abstract: A distributed client/server system
version: 3.04
version_from: lib/Dicop.pm
license: gpl
distribution_type: module
generated_by: Dicop-Server version 3.04
installdirs: none
requires:
  Dicop::Base: 3.04
  Digest::MD5: 2.09
  File::Spec: 0.82
  HTML::Tagset: 3.03
  HTTP::Request: 1.24
  Linux::Cpuinfo: 1.7
  Mail::Sendmail: 0.77
  Math::BigInt: 1.77
  Math::String: 1.27
  Math::String::Charset::Wordlist: 0.07
  Net::Server: 0.86
  Term::ReadLine: 1.01
  Test::Simple: 0.47
  Time::HiRes: 1.2
