  body, a, h4, h3, h2, h1, p, div, span {
    font-family: helvetica, sans-serif;
    }
  h1, h2, h3, h4, h5, h6, h7 {
    border: solid 1px;
    border-bottom: none;
    width: 45%; 
    padding: 0.2em;
    padding-left: 0.5em;
    margin: 0em;
    -moz-border-radius: 0em 1em 0em 0px;
    }
  div.clear {
    clear: both;
    }
  div.menu {
    border: solid 1px; 
    padding: 0.5em;
    margin: 0em;
    float: right;
    text-align: right;
    -moz-border-radius: 0em 1em 0px 0px;
    }
  div.text {
    border: solid 1px; 
    padding: 0.5em;
    margin: 0em;
    margin-bottom: 0.5em;
    -moz-border-radius: 0px 1em 0px 0px;
    }
  div.percent {
    width: 100px;
    border: 1px solid;
    height: 0.5em;
    padding: 0;
    margin: 0;
    }
  div.footerhead { display: none; }
  div.footer {
    border: solid 1px; 
    padding: 0.5m;
    padding-top: 0.5m;
    margin: 0em;
    margin-top: 0.5em;
    -moz-border-radius: 0px 1em 0px 0px;
    }
  table {
    border-collapse: collapse;
    margin: 0em;
    border: solid 1px; 
    margin-bottom: 0.5em;
    margin-left: 0.5em;
    padding: 0px;
    cell-spacing: 0;
    cell-padding: 0;
    }
  span.percent {
    min-width: 1px;
    max-width: 100px;
    border: none;
    height: 0.5em;
    padding: 0;
    margin: 0;
    float: left;
    }
  input.submit, input.browse {
    margin-left: 1em;
    }
  input.reset {
    margin-left: 2em;
    }
  input.submit, input.browse, input.refresh, input.reset {
    border: 1px solid;
    padding: 3px;
    cursor: pointer;
    }
  table.menu {
    float: right;
    margin: 0;
    padding: 0;
    }
  table.auth {
    margin-bottom: 0.5em;
    }
  table.edit {
    margin: 0.5em;
    }
  td.editfieldname, td.editfieldname1, td.editfieldname2 {
    padding: 2px;
    padding-left: 0.5em;
    padding-right: 0.5em;
    text-align: right;
    border-right: 1px solid;
    border-left: none;
    }
  td.editfield {
    padding: 4px;
    padding-left: 0.5em;
    padding-right: 0.5em;
    border-left: none;
    }
  td.indend {
    width: 1em;
    border-right: none;
    }
  td.code
    {
    font-family: courier-new, courier, monospaced;
    font-size: 0.5em;
    text-align: right;
    }
  tr {
    margin: 0;
    padding: 0px;
    }   
  td {
    font-size: 0.8em;
    margin: 0px;
    padding: 2px;
    padding-left: 4px;
    padding-right: 4px;
    border: 1px solid;
    }
  td.id {
    text-align: right;
    }
  th {
    font-size: 0.8em;
    margin: 0px;
    padding: 3px;
    border: 1px solid;
    }
  ul {
    list-style-type: square;
    }
