  h1, h2, h3, h4, h5, h6, h7 {
    position: relative; top: 0.4em; left: 30px;
    padding-bottom: 0.3em;
    padding-top: 0.2em;
    opacity:0.8;
    -moz-opacity: 0.8;
    filter: alpha(opacity=80);
    -moz-border-radius: 1em 1em 1em 1em;
    border: 2px solid;
    }
  div.menu {
    -moz-border-radius: 1em 1em 1em 1em;
    opacity:0.8;
    -moz-opacity: 0.8;
    filter: alpha(opacity=80);
    border: 2px solid black;
    color: white;
    padding-left: 0.8em;
    padding-right: 0.8em;
    position: relative; top: 0.4em; left: -0.5em;
    }
  div.text {
    -moz-border-radius: 1em 1em 1em 1em;
    padding-top: 1.5em;
    }
  ul {
    list-style-type: disc;
    }
  th {
    border: 1px solid;
    }
  p.footer {
    padding-top: 0.1em;
    padding-bottom: 0.2em;
    }
  div.footer {
    border: solid 1px; 
    margin: 0px;
    padding-top: 0.2em;
    padding-bottom: 0.1em;
    -moz-border-radius: 1em 1em 1em 1em;
    }
  input.submit, input.browse, input.reset, input.refresh {
    -moz-border-radius: 0.8em 0.8em 0.8em 0.8em;
    border: 1px solid;
    padding: 4px;
    cursor: pointer;
    }
  a:link { 
    padding: 2px;
    }
  a:link.h { 
    padding: 2px;
    }
  a:hover.m { 
    border: 0px;
    margin: 0px;
    padding: 2px;
    }
  a:hover { 
    border: 0px;
    margin: 0px;
    }
  a:hover.h { 
    border: 0px;
    margin: 0px;
    }

