
<form action="##self##" method="POST">

<span style="float: left">
<table class="auth">
<tr>
 <th class="auth">Username:</td>
 <td class="auth" align="right"><input type=text name="auth-user" value="" maxlength=32 size=32 title="Enter your username to authenticate yourself"></td>
 <th class="auth" align="right">Password:</td>
 <td><input type=password name="auth-pass" value="" maxlength=128 size=32 title="Enter your password to authenticate yourself"></td>
</tr>
</table>
</span>

<input type=hidden name="style" value="##style##">

