  body {
    background: white;
    color: black;
    }
  body, a, h4, h3, h2, h1, p, div, span {
    font-family: helvetica, sans-serif;
    }
  hr.pushdown { display: block; clear: left; margin: 0; visibility: hidden; }
  h1, h2, h3, h4, h5, h6, h7 {
    background: #ff9000;
    border: solid 1px black;
    border-color: black;
    border-bottom: none;
    width: 45%; 
    padding: 0.2em;
    padding-left: 0.5em;
    margin: 0em;
    color: black;
    }
  div.clear {
    clear: both;
    }
  div.menu {
    background: #ff9000;
    border: solid 1px black; 
    padding: 0.5em;
    margin: 0em;
    float: right;
    text-align: right;
    color: black;
    }
  div.text {
    background: #ffffd0;
    border: solid 1px black; 
    padding: 0.5em;
    margin: 0em;
    margin-bottom: 0.5em;
    color: black;
    }
  div.percent {
    width: 100px;
    border: 1px solid black;
    height: 0.5em;
    padding: 0;
    margin: 0;
    }
  div.footerhead {
    margin: 0em;
    padding: 0em;
    display: none;
    }
  div.footer {
    background: #f08000;
    border: solid 1px black; 
    padding: 0.5m;
    padding-top: 0.3m;
    margin: 0em;
    color: #303030; 
    text-align: center;
    }
  table {
    border-collapse: collapse;
    margin: 0em;
    border: solid 1px black; 
    margin-bottom: 0.5em;
    margin-left: 0.5em;
    padding: 0px;
    cell-spacing: 0;
    cell-padding: 0;
    }
  span.percent {
    background: #ff0000;
    min-width: 1px;
    max-width: 100px;
    border: none;
    height: 0.5em;
    padding: 0;
    margin: 0;
    float: left;
    }
  input:focus, select:focus, input.submit:focus, input.reset:focus, input.browse:focus, input.refresh:focus { background: #c03000; color: white; }
  input:hover, select:hover, input.submit:hover, input.reset:hover, input.browse:hover, input.refresh:hover { background: #c03000; color: white; }
  input.submit, input.browse {
    margin-left: 1em;
    }
  input.reset {
    margin-left: 2em;
    }
  input.submit, input.browse, input.refresh, input.reset {
    background: #ff9000;
    color: black;
    border: 1px solid black;
    padding: 3px;
    cursor: pointer;
    }
  table.menu {
    float: right;
    margin: 0;
    padding: 0;
    }
  table.auth {
    margin-bottom: 0.5em;
    }
  table.edit {
    margin: 0.5em;
    }
  td.editfieldname, td.editfieldname1, td.editfieldname2 {
    padding: 2px;
    padding-left: 0.5em;
    padding-right: 0.5em;
    text-align: right;
    border-right: 1px solid grey;
    border-left: none;
    }
  td.editfieldname1, td.editfieldname2 {
    background: #ffd070;
    }
  td.editfield {
    padding: 4px;
    padding-left: 0.5em;
    padding-right: 0.5em;
    border-left: none;
    }
  td.indend {
    width: 1em;
    border-right: none;
    background: #ffd070;
    }
  td.code
    {
    font-family: courier-new, courier, monospaced;
    font-size: 0.5em;
    text-align: right;
    }
  th.auth {
    padding: 5px;
    background: #ff9000;
    }
  tr {
    margin: 0;
    padding: 0;
    }   
  td {
    font-size: 0.8em;
    margin: 0px;
    padding: 2px;
    padding-left: 4px;
    padding-right: 4px;
    border: 1px solid black;
    background: #fff0a0;
    }
  td.id {
    text-align: right;
    }
  td.highlight	{ background: #ffffff; }
  tr.odd 	{ background: #ffffe0; }
  td.noreturn	{ background: #ff8020; }
  td.unknown	{ background: #e0e0e0; }
  td.offline	{ background: #ff0000; }
  td.online	{ background: #00ff00; }
  td.nocon	{ background: #fff000; }
  td.tobedone	{ background: #80ff80; }
  td.solved	{ background: #ff80ff; }
  td.suspended	{ background: #ffff80; }
  td.failed	{ background: #ff8080; }
  td.bad	{ background: #ff0000; }
  td.verify	{ background: #40ff40; }
  td.issued	{ background: #ffff80; }
  td.done	{ background: #e0ffe0; }
  td.waiting	{ background: #40d040; }
  th {
    font-size: 0.8em;
    background: #ff9000;
    margin: 0px;
    padding: 3px;
    border: 1px solid black;
    color: black;
    }
  ul {
    list-style-type: square;
    }
  li { padding-bottom: 0.2em; }
  td.DIR_FILE
    {
    background: #ffffff;
    border: 1px solid;
    border-top: none;
    }
  td.DIR_DIR, td.DIR_UPDIR
    {
    background: #10d0e0;
    border: 1px solid;
    border-top: none;
    }
  td.DIR
    {
    padding-left: 0.3em;
    text-align: left;
    border: none;
    border-bottom: 1px solid;
    }
  td.DIR_ODD
    {
    background: #ffffd0;
    padding-left: 0.3em;
    text-align: left;
    border: none;
    border-bottom: 1px solid;
    }
  td.DIR_RIGHT
    {
    text-align: right;
    padding-left: 1em;
    padding-right: 0.3em;
    border: none;
    border-bottom: 1px solid;
    border-right: 1px solid;
    }
  td.DIR_RIGHT_ODD
    {
    background: #ffffd0;
    text-align: right;
    padding-left: 1em;
    padding-right: 0.3em;
    border: none;
    border-bottom: 1px solid;
    border-right: 1px solid;
    }
  li.help {
    margin-bottom: 0.3em;
    }
  p {
    margin: 0em;
    padding: 0.5em;
    color: #303030
    }
  p.small, li.small, ul.small {
    font-family: courier-new, courier, monospaced;
    font-size: 0.5em;
    }
  span.generated {
    font-size: 0.25em;
    margin: 0em;
    padding: 0em;
    padding-bottom: 0.2em;
    text-align: center;
    }
  span.footer {
    margin: 0em;
    padding: 1px;
    font-size: 0.8em;
    border: 0;
    }
  pre, pre.error {
    margin: 0.3em;
    margin-bottom: 0em;
    padding: 2px;
    margin-left: 1.0em;
    }
  pre.error {
    border: solid 1px black;
    }
  a:link { 
    color: #404040;
    padding: 1px;
    margin: 0;
    }
  a:visited { 
    color: #202020;
    padding: 1px;
    margin: 0;
    }
  a:hover.m { 
    background-color: #ffff20;
    border: black 1px solid;
    padding: 4px;
    margin: 0;
    color: black;
    }
  a:hover { 
    border: 0;
    padding: 1px;
    background-color: black;
    margin: 0;
    color: #ff8020;
    }
