
<tr>
  ##indend_filler##<td class="editfieldname##fieldindend##" colspan=##indend##>
    ##field##:
  </td>

  <td class="editfield" colspan=##-indend##>
    <input type=text name="##fieldname##" value="##value##" size=##size## maxlength=##fieldmaxlen##><input class="browse" type=submit name="submit_cmd_status;type_file;style_##style##;browse_target;targetfield_##fieldname##;path_./##safevalue##=>##formname##" title="Click to select a file from the file tree" value="Browse">
  </td>

  <td class="editfieldhelp">
    ##fieldhelp##
  </td>
</tr>

