
<tr>
 ##indend_filler##<td class="editfieldname##fieldindend##" colspan=##indend##>
  ##field##:
 </td>

 <td class="editfield" colspan=##-indend##>
  <select name="##fieldname##">
  <!-- start -->
   <option value="##validvalue##"##selected##>##validname##
  <!-- end -->
  </select>
  <input class="refresh" type="submit" name="submit_##formname##;style_##style##=>" title="Click to refresh form if you changed this setting" value="Refresh">
 </td>

 <td class="editfieldhelp">
  ##fieldhelp##
 </td>
</tr>

