
<div class="menu">
<a class="h" href="##selfform_help##" title="Go to the help overview">Help</a> |
<a class="h" href="##selfform_##type####" title="Add a new ##type##">Add</a> |
<a class="h" href="##selfform_##type##;id_##id####" title="Edit settings of this ##type##">Edit</a> |
<a class="h" href="##selfconfirm_##type##;id_##id####" title="Delete this ##type##">Delete</a>
</div>

<!-- autoremovethisline --> <div class="clear"></div>
