
<table class="menu">
<tr>

<td class="failed">
<p class="small">
<a href="##selfstatus_main##;filter_SOLVED,TOBEDONE,SUSPENDED" title="View all jobs without a result">Failed</a>
</p>
</td>

<td class="solved">
<p class="small">
<a href="##selfstatus_main##;filter_FAILED,TOBEDONE,SUSPENDED" title="View all solved jobs">Solved</A>
</p>
</td>

<td class="tobedone">
<p class="small">
 <a href="##selfstatus_main##;filter_FAILED,SOLVED,SUSPENDED" title="View all currently running jobs">Running</a>
</p>
</td>

<td class="suspended">
<p class="small">
 <a href="##selfstatus_main##;filter_FAILED,TOBEDONE,SOLVED" title="View all suspended jobs">Suspended</a>
</p>
</td>
</tr>

</table>

<div class="clear"></div>
