
<div class="menu">
<a class="h" href="##selfform_client;id_##id####" title="Edit settings of this client">Edit</a> |
<a class="h" href="##selfconfirm_client;id_##id####" title="Delete this client">Delete</a> |
<a class="h" href="##selfconfirmterminate_client;id_##id####" title="Tell client to terminate itself">Terminate</a> |
<a class="h" href="##selfconfirmreset_client;id_##id####" title="Reset this client's status">Reset</a>
</div>

<!-- autoremovethisline --> <div class="clear"></div>
