
<div class="menu">
<a class="h" href="##selfform_help##" title="Go to the help overview">Help</a> |
<a class="h" href="##selfform_charset##" title="Add a new charset">Add</a> |
<a class="h" href="##selfform_charset;id_##id####" title="Edit settings of this charset">Edit</a> |
<a class="h" href="##selfconfirm_charset;id_##id####" title="Delete this charset">Delete</a>
</div>

<!-- autoremovethisline --> <div class="clear"></div>
