
<table class="menu">
<tr>

<td class="all">
<p class="small">
 <a href="##selfstatus_case##;id_##id##;filter_DONE" title="View all jobs">All</a>
</p>
</td>

<td class="failed">
<p class="small">
<a href="##selfstatus_case##;id_##id##;filter_SOLVED,TOBEDONE,SUSPENDED" title="View all jobs from this case without a result">Failed</a>
</p>
</td>

<td class="solved">
<p class="small">
<a href="##selfstatus_case##;id_##id##;filter_FAILED,TOBEDONE,SUSPENDED" title="View all solved jobs from this case">Solved</A>
</p>
</td>

<td class="tobedone">
<p class="small">
 <a href="##selfstatus_case##;id_##id##;filter_FAILED,SOLVED,SUSPENDED" title="View all currently running jobs from this case">Running</a>
</p>
</td>

<td class="suspended">
<p class="small">
 <a href="##selfstatus_case##;id_##id##;filter_FAILED,TOBEDONE,SOLVED" title="View all suspended jobs from this case">Suspended</a>
</p>
</td>

</tr>

</table>

<!-- autoremovethisline --> <div class="clear"></div>
