
<tr>
<th align=right>##param0##:</th>
<td>
 <select name="cpos##param0##">
  <option value="-1">Don't use</option>
  <option value="1">Append</option>
  <option value="0">Prepend</option>
 </select>
</td>

<td>
<select name="charset" type=simple,grouped>
<option name="cset##param0##" value="##charsetid##">##charsetdescription##</option>
</select>
</td>

<td align=right>Start length:&nbsp;
<input name="cstart##param0##" value="1" maxlen=2 size=3>
</td>

<td align=right>End length:&nbsp;
<input name="cend##param0##" value="1" maxlen=2 size=3>
</td>

</tr>
